#!/usr/bin/env ruby
# frozen_string_literal: true

require 'linear'
Rubyists::Linear::L :cli
begin
  Dir.mktmpdir(Process.pid.to_s) do |dir|
    Rubyists::Linear.tmpdir = dir
    Dry::CLI.new(Rubyists::Linear::CLI).call
  end
ensure
  FileUtils.rm_rf(Rubyists::Linear.tmpdir) if Rubyists::Linear.tmpdir.exist?
end
